name: Release Bosh Release

on:
    workflow_dispatch: { }
    push:
      branches:
        - "main"

env:
    # Default image for the Chart
    DOCKER_IMAGE_NAME: mimirrules-controller
    DOCKER_REGISTRY: ghcr.io/springernature/o11y-rules-telemetry-operator
    DOCKER_BUILD_DIR: '.'

permissions: {}

jobs:
  make:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        lfs: true
    
    - name: Create final bosh release
      uses: orange-cloudfoundry/bosh-release-action@v2
      with:
        target_branch: main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
